### ISSUE TITLE
Randomly fails on different projects

### ISSUE THREAD

**Issue by Tailslide** [Jnesselr/fusion-360-total-exporter#10] opened 2020-09-19 01:28 UTC
Seems to fail on a different project every time I run it.

![image](https://user-images.githubusercontent.com/5757188/93656097-0f6f4980-f9e5-11ea-81a9-d310baee389b.png)

**Comment by Jnesselr** [comment] 2020-09-19 01:40
Seems like a duplicate of #4

**Closed as completed by Jnesselr** 2020-09-19 01:40 UTC
Labels: bug, duplicate
